ND_Police
ND-Framework/ND_Police pull request #26
Opened 2024-12-07 01:40 UTC by Cljones2

2024-12-07 01:42 UTC, Cljones2 commented
Just an update where you can cuff a player and search a player when cuffed 
until there's a new update to nd police

2025-02-01 21:24 UTC, Andyyy7666 commented
Did you mean to pr this or is this just an old fix for something?

2025-03-27 05:50 UTC, WEEZOOKARP commented
looks like this is just replacing the entire cuff script with the esx_policejob one

2025-06-22 08:13 UTC, marshular requested changes
these changes completely alter and ruin the script. i recommend just closing this pr

2025-09-03 15:49 UTC, closed without merging